import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";

const pixelify = Pixelify_Sans({
  variable: "--font-pixelify_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chase.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pixelify.variable} antialiased dark`}>
        {children}
      </body>
    </html>
  );
}
